# Aktifkan Gzip
gzip on;
gzip_bypasses_gzip_on off;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 5;
gzip_min_length 256;

# Daftarkan tipe file yang wajib dikompresi (termasuk .onnx / application/octet-stream)
gzip_types
    text/plain
    text/css
    application/json
    application/javascript
    text/xml
    application/xml
    application/xml+rss
    text/javascript
    application/octet-stream;